name: select-runs-on-action
description: takes inputs for repository and mapping file to dynamically select the runs-on runner
author: William Sanders

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: red

# Define your inputs here.
inputs:
  repository:
    description: GitHub repository name
    required: true
  default-runs-on:
    description: Default runs_on value from veracode workflow inputs
    required: true
  runs-on-mapping-yaml:
    description: YAML mapping file for runs-on configuration
    required: true
    default: 'runs-on-mapping.yaml'
  debug:
    # 'true' || 'false'
    description: Enable advanced debug output
    required: false

# Define your outputs here.
outputs:
  runs-on:
    description: runs_on runner selection from YAML mapping file

runs:
  using: node24
  main: dist/index.js
